# Generated by Django 3.2 on 2022-12-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='on_tickets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
