# Generated by Django 3.2 on 2022-12-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_payment_on_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
